using StoreOnLine.Domain.Base;

namespace StoreOnLine.Domain.Enums
{
    public enum BoostrapCss
    {
        [StringValue("col-xs-1")]
        Colxs1,
        [StringValue("col-xs-2")]
        Colxs2,
        [StringValue("col-xs-3")]
        Colxs3,
        [StringValue("col-xs-4")]
        Colxs4,
        [StringValue("col-xs-5")]
        Colxs5,
        [StringValue("col-xs-6")]
        Colxs6,
        [StringValue("col-xs-7")]
        Colxs7,
        [StringValue("col-xs-8")]
        Colxs8,
        [StringValue("col-xs-9")]
        Colxs9,
        [StringValue("col-xs-10")]
        Colxs10,
        [StringValue("col-xs-11")]
        Colxs11,
        [StringValue("col-xs-12")]
        Colxs12,
        [StringValue("col-sm-1")]
        Colsm1,
        [StringValue("col-sm-2")]
        Colsm2,
        [StringValue("col-sm-3")]
        Colsm3,
        [StringValue("col-sm-4")]
        Colsm4,
        [StringValue("col-sm-5")]
        Colsm5,
        [StringValue("col-sm-6")]
        Colsm6,
        [StringValue("col-sm-7")]
        Colsm7,
        [StringValue("col-sm-8")]
        Colsm8,
        [StringValue("col-sm-9")]
        Colsm9,
        [StringValue("col-sm-10")]
        Colsm10,
        [StringValue("col-sm-11")]
        Colsm11,
        [StringValue("col-sm-12")]
        Colsm12,
        [StringValue("col-md-1")]
        Colmd1,
        [StringValue("col-md-2")]
        Colmd2,
        [StringValue("col-md-3")]
        Colmd3,
        [StringValue("col-md-4")]
        Colmd4,
        [StringValue("col-md-5")]
        Colmd5,
        [StringValue("col-md-6")]
        Colmd6,
        [StringValue("col-md-7")]
        Colmd7,
        [StringValue("col-md-8")]
        Colmd8,
        [StringValue("col-md-9")]
        Colmd9,
        [StringValue("col-md-10")]
        Colmd10,
        [StringValue("col-md-11")]
        Colmd11,
        [StringValue("col-md-12")]
        Colmd12,
        [StringValue("col-lg-1")]
        Collg1,
        [StringValue("col-lg-2")]
        Collg2,
        [StringValue("col-lg-3")]
        Collg3,
        [StringValue("col-lg-4")]
        Collg4,
        [StringValue("col-lg-5")]
        Collg5,
        [StringValue("col-lg-6")]
        Collg6,
        [StringValue("col-lg-7")]
        Collg7,
        [StringValue("col-lg-8")]
        Collg8,
        [StringValue("col-lg-9")]
        Collg9,
        [StringValue("col-lg-10")]
        Collg10,
        [StringValue("col-lg-11")]
        Collg11,
        [StringValue("col-lg-12")]
        Collg12
    }
}
